tableName = 'RolesUsers'

module.exports =
  up: (migration, DataTypes, done) ->
    columns =
      id:
        type: DataTypes.INTEGER
        allowNull: false
        primaryKey: true
        autoIncrement: true
        _autoGenerated: true

      RoleId:
        type: DataTypes.INTEGER
        allowNull: false
        references: "Role"
        referencesKey: "id"

      UserId:
        type: DataTypes.INTEGER
        allowNull: false
        references: "User"
        referencesKey: "id"

      approved:
        type: DataTypes.DATE
        allowNull: true

      rejected:
        type: DataTypes.DATE
        allowNull: true

      rejectionReason:
        type: DataTypes.TEXT
        allowNull: true

      meta:
        type: DataTypes.TEXT
        allowNull: false

      createdAt:
        type: DataTypes.DATE
        allowNull: false

      updatedAt:
        type: DataTypes.DATE
        allowNull: false

    migration.createTable(tableName, columns).complete(done)

  down: (migration, DataTypes, done) ->
    migration.dropTable(tableName).complete(done)
