tableName = 'Users'

module.exports =
  up: (migration, DataTypes, done) ->
    columns =
      id:
        type: DataTypes.INTEGER
        allowNull: false
        primaryKey: true
        autoIncrement: true
        _autoGenerated: true

      email:
        type: DataTypes.STRING
        allowNull: false
        unique: true

      username:
        type: DataTypes.STRING
        allowNull: false
        unique: true

      password:
        type: DataTypes.STRING
        allowNull: false

      paidUntil:
        type: DataTypes.DATE
        allowNull: true

      fullname:
        type: DataTypes.STRING
        allowNull: true

      address:
        type: DataTypes.TEXT
        allowNull: true

      approved:
        type: DataTypes.DATE
        allowNull: true

      meta:
        type: DataTypes.TEXT
        allowNull: false

      createdAt:
        type: DataTypes.DATE
        allowNull: false

      updatedAt:
        type: DataTypes.DATE
        allowNull: false

    migration.createTable(tableName, columns).complete(done)

  down: (migration, DataTypes, done) ->
    migration.dropTable(tableName).complete(done)
