tableName = 'Roles'

module.exports =
  up: (migration, DataTypes, done) ->
    columns =
      id:
        type: DataTypes.INTEGER
        allowNull: false
        primaryKey: true
        autoIncrement: true
        _autoGenerated: true

      name:
        type: DataTypes.STRING
        allowNull: false
        unique: true

      meta:
        type: DataTypes.TEXT
        allowNull: false

      createdAt:
        type: DataTypes.DATE
        allowNull: false

      updatedAt:
        type: DataTypes.DATE
        allowNull: false

    migration.createTable(tableName, columns).complete(done)

  down: (migration, DataTypes, done) ->
    migration.dropTable(tableName).complete(done)
